
<style type="text/css" media="screen">
	.mw_rwp_promotion{
		background: #EFF5EA ;
		color: #3D6611;
		border: 1px solid #446423;
		padding: 8px 8px 8px 8px;
		margin-bottom: 15px;
		font-weight: bold;
		font-size: 11px;
		-webkit-border-radius: 5px;
		-moz-border-radius: 5px;
		border-radius: 5px;
		box-shadow: 0 0 2px 1px #446423
	}
    ul#mw_rewardpoint_promotion_message {
      	margin: 0;
      	padding: 0;
      	position: relative;
    	over-flow: hidden
    }
      
      ul#mw_rewardpoint_promotion_message li {
        display: block;
        list-style: none;
        margin: 0;
        padding: 0px 0px 0px 30px;
        position: relative !important;
      	background: url("<?php echo $this->getSkinUrl('images/i_msg-success.gif') ?>") no-repeat 10px 4px;
		line-height: 24px;
    }
            
  </style>
  <script type="text/javascript">
        /*<![CDATA[*/
    	new SlideShow('mw_rewardpoint_promotion_message');
        /*]]>*/
  </script>
  
<?php
	$list_messages = $this->getMessageRules();
    if(sizeof($list_messages)){?>

	<div class="mw_rwp_promotion">
        <ul id="mw_rewardpoint_promotion_message" >
            <?php foreach($list_messages as $list_message){?>
            <li><?php echo $list_message;?></li>
            <?php }?>
        </ul>
    </div>
    <?php
    }
	?>