<?php $quote = Mage::getSingleton('checkout/session')->getQuote();
	  $store_id = Mage::app()->getStore()->getId();
	  $rewardpoints = $quote->getMwRewardpoint();
	  $earn_rewardpoint = (int)$quote->getEarnRewardpoint();
	  /*
	  $reward_point_sell_product = $quote->getMwRewardpointSellProduct();
	  $points = 0;
	  if ($quote->getPayment()->hasMethodInstance()){            
		  $paymentMethod = $quote->getPayment()->getMethodInstance();
		  if($paymentMethod->getCode() == 'rewardpoints') {
	
		  	 $base_grand_total = $quote->getBaseGrandTotal();
		  	 $points = (int)Mage::helper('rewardpoints')->roundPoints(Mage::helper('rewardpoints')->exchangeMoneysToPoints($base_grand_total,$store_id),$store_id);
		  } 	
	  }
	  $total_reward_point = $rewardpoints + $reward_point_sell_product + $points;
	  */
	  ?>
<?php if($rewardpoints):?>
	<?php //$money = Mage::helper('rewardpoints')->getCheckoutSession()->getDiscount()
		  $money = $quote->getMwRewardpointDiscount();
		?>
	<tr>
	    <td colspan="3" class="a-right" colspan="1"><?php echo Mage::helper("rewardpoints")->__("You Redeem");?></td>
	    <td class="a-right"><span class="price"><?php echo Mage::helper('rewardpoints')->formatPoints($rewardpoints,$store_id)?></span></td>
	</tr>
<?php endif;?>

<?php //if($total_reward_point):?>
	<!--  <tr>
	    <td colspan="3" class="a-right" colspan="1"><b><?php //echo Mage::helper("rewardpoints")->__("Total Points");?></b></td>
	    <td class="a-right"><span class="price"><?php //echo Mage::helper('rewardpoints')->formatPoints($total_reward_point,$store_id)?></span></td>
	</tr> -->
<?php //endif;?>
<?php if($earn_rewardpoint):?>
	<tr>
	    <td colspan="3" class="a-right" colspan="1"><?php echo Mage::helper("rewardpoints")->__("You Earn");?></td>
	    <td class="a-right"><span class="price"><?php echo Mage::helper('rewardpoints')->formatPoints($earn_rewardpoint,$store_id)?></span></td>
	</tr>
<?php endif;?>